# Generated by Django 4.0.5 on 2022-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField()),
                ('distribution_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('mobile_number', models.PositiveBigIntegerField()),
                ('landline_number', models.PositiveBigIntegerField()),
                ('caliper', models.CharField(max_length=50)),
                ('wheelchair', models.CharField(max_length=10)),
                ('tricycle', models.CharField(max_length=10)),
                ('cruthces', models.CharField(max_length=10)),
                ('hearing_aids', models.CharField(max_length=10)),
                ('hands', models.CharField(max_length=10)),
                ('above_knee_jaipur_foot', models.CharField(max_length=20)),
                ('below_knee_jaipur_foot', models.CharField(max_length=20)),
                ('ratnanidhi_leg', models.CharField(max_length=20)),
                ('ls_belt', models.CharField(max_length=10)),
                ('knee_cap', models.CharField(max_length=10)),
                ('soft_collor', models.CharField(max_length=10)),
                ('maritial_status', models.CharField(default=None, max_length=10)),
                ('educational_background', models.CharField(default=None, max_length=25)),
            ],
        ),
    ]
