# Generated by Django 4.0.5 on 2022-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userdata_above_knee_jaipur_foot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='landline_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
