# Generated by Django 4.0.5 on 2022-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userdata_landline_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='educational_background',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='maritial_status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
