# Generated by Django 4.0.5 on 2022-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userdata_educational_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pincode',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
