# Generated by Django 4.0.5 on 2022-06-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userdata_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='link',
            field=models.CharField(default='https://wa.me/91<django.db.models.fields.PositiveBigIntegerField>', max_length=30),
        ),
    ]
